### ISSUE TITLE
API Issues??

### ISSUE THREAD

**Issue by robotica72** [homespun/ring-alarm#7]
So far the API has been working great for me - added it to my own API server for using Google Home and it started to fail a few days ago - I simplified the script just in case it was an issue in my code but I still have the same issue - Running the code always throws the following error:

SyntaxError: Unexpected end of input
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)

Is there an update to the API coming??

**Comment by acolytec3** [comment]
Not sure about the version of the code in this repo but I've upgraded to the variant from [PR 2](https://github.com/homespun/ring-alarm/pull/5) and it's working great.

**Comment by robotica72** [comment]
Thanks - Oddly enough my old script works now that I did try the retries 0 to 5 on my PC - Im actually running my API server in a container on Kuberetes.
